### ISSUE TITLE
Error with python while trying to run script for first time...

### ISSUE THREAD

**Issue by conorfenlon** [mikeycal/the-video-editors-render-script-for-blender#8]
Hi Mikey, I can't seem to run this script without getting an error. This is the first time I'm attempting to use the script. I'll post the traceback below.
I'm using Ubuntu 16.04 LTS

I'm not very python savvy, so I would appreciate any hep you might be able to offer me. Thanks in advance.

blender -b 1.blend -P video_editors_render_script.py
found bundled python: /usr/lib/blender/2.79/python
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/blender/2.79/python/lib/python3.5/importlib/__init__.py", line 57, in <module>
    import types
  File "/usr/lib/blender/2.79/python/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/usr/lib/blender/2.79/python/lib/python3.5/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/usr/lib/blender/2.79/python/lib/python3.5/weakref.py", line 12, in <module>
    from _weakref import (
ImportError: cannot import name '_remove_dead_weakref'

During handling of the above exception, another exception occurred:

SystemError: <built-in function register> returned a result with an error set
Read blend: /home/conor/Desktop/Render Script/1.blend
Traceback (most recent call last):
  File "/home/conor/Desktop/Render Script/video_editors_render_script.py", line 79, in <module>
    import platform                                                                #  | Bash Shell, Blender and FFmpeg.
  File "/usr/lib/blender/2.79/python/lib/python3.5/platform.py", line 117, in <module>
    import sys, os, re, subprocess
  File "/usr/lib/blender/2.79/python/lib/python3.5/subprocess.py", line 50, in <module>
    import signal
  File "/usr/lib/blender/2.79/python/lib/python3.5/signal.py", line 3, in <module>
    from functools import wraps as _wraps
  File "/usr/lib/blender/2.79/python/lib/python3.5/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/usr/lib/blender/2.79/python/lib/python3.5/weakref.py", line 12, in <module>
    from _weakref import (
ImportError: cannot import name '_remove_dead_weakref'

Blender quit

**Comment by Flaick** [comment]
Did you resolve the problem, I have the same issue here

**Comment by mikeycal** [comment]
@Flaick 
Make sure that you download the latest copy of the script. I am also primarily running on Ubuntu Linux (20.04LTS), so I usually notice issues there first. :)

You can Right Click and "Save Link As..." the following link for the latest version of my script:
https://github.com/mikeycal/the-video-editors-render-script-for-blender/raw/master/video_editors_render_script.py

**Comment by Flaick** [comment]
Thank you I will try that
